version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
    image: arba-frontend
    ports:
      - 4173:4173
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=development
